### PR TITLE
Adding 'index' parameter so we can pick what index to search.

### PR DESCRIPTION
**Pull request by pieterlange**
Defaults safely to original behaviour (query everything)

### CODE REVIEW

**Comment by pieterlange** [comment]
I have finally signed the CLA now. Somehow missed the message.

**Comment by jordansissel** [comment]
@pieterlange The email used in the git commit for this PR is not in our CLA database. I found another email with your name on it, but it doesn't match the one in the commit (see `git log` or this url https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-filter-elasticsearch/pull/16.patch - the `From:` line)

**Comment by purbon** [comment]
closing this PR as the CLA is still missing for long time, happy to reopen when this is fixed.

**Comment by karmi** [comment]
Hi @pieterlange, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/16.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by purbon** [comment]
Closing this for now as the CLA signature has been an issue for long time, happy to reopen this when this is sorted out! looking forward to it.

**Comment by pieterlange** [comment]
Email used was with a previous client (no longer have access to this account). This is a small patch for a plugin barely anyone uses (i think?). If there's any interest i can re-author it.

**Comment by pieterlange** [comment]
#31 fixes this too. :)

**Pull request closed without merging**
