### PR TITLE
Allow access to meta-fields

### LINKED ISSUE #57: Add ability to access _id from the queried event
According to @ph there is no way to access _id from the document that was queried, and there should be.

### PR DESCRIPTION
**Pull request by pemontto**
This closes #57 by adding a meta_fields config to extract [event meta-fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-fields.html)

### CODE REVIEW

**Comment by magnusbaeck** [comment]
How about using the same configuration interface as the elasticsearch input (`docinfo`, `docinfo_fields`, and `docinfo_target`)?

**Comment by pemontto** [comment]
Thanks @magnusbaeck, will take a look

**Comment by pemontto** [comment]
@magnusbaeck After thinking about it only `docinfo_fields` is relevant for this plugin. In this case it matches the existing behaviour of the existing `fields` configuration option.

**Comment by pemontto** [comment]
No longer necessary, #83 has been merged

**Pull request closed without merging**
