### PR TITLE
Update index.asciidoc

### PR DESCRIPTION
**Pull request by pmusa**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by webmat** [comment]
Thanks for taking the time to send this over.

This attribute is actually still an `array` (expecting a list of tuples). These kinds of arrays support the hash-like notation as well, which is the most readable way to specify those.

Although the `array` field type is deprecated, we can't just move the attribute type to `hash`. This would break compatibility for anyone using the array notation with tuples.

**Comment by pmusa** [comment]
Maybe we can make it more clear in the docs then, with an example. It took me almost 10 minutes to understand the error and fix it. The doc description make it sound that field names will be preserved which is not the case.

**Comment by webmat** [comment]
Good point. The intro section of this plugin has examples of using `fields`, but you're right that there are no examples in the description of the attribute itself. I'll improve the docs accordingly. Thanks for the feedback 👍

**Comment by webmat** [comment]
Let me know what you think about #101

**Comment by webmat** [comment]
The suggested fix to the documentation has been merged. Should be reflected on elastic.co later today.

**Comment by pmusa** [comment]
thank you!

**Pull request closed without merging**
