### PR TITLE
adding an option to specify an index, fix of a huge mistake in current documentation, rewriting of hosts handling to have working ssl in Logstash 2.3, adding transport_options to enable advanced underlying Transport Options.

### PR DESCRIPTION
**Pull request by jehuty0shift**
Hello, 
This is a pretty simple Pull Request to enable a new setting "index". This setting allows you to specify which Elasticsearch Index you want to query.   

PS. I have signed the Logstash agreement shortly. Is it possible to check it again ?

### CODE REVIEW

**Comment by karmi** [comment]
Hi @jehuty0shift, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/31.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by jehuty0shift** [comment]
Hi @karmi, Thanks for your reply ! Sorry for that, I just added my commit e-mail to my account then.

**Comment by jehuty0shift** [comment]
I change the implementation of hosts and options to have a working ssl in Logstash 2.3, I added Transport options option to let users provide more advanced options in the Default Faraday Transport used by the Elasticsearch Client. User and Password are handle directly by the Elasticsearch Client.

**Comment by purbon** [comment]
Thanks a lot for your contribution @jehuty0shift I'm doing some maintenance here and took some of your commits for a bigger PR where I will include some changes pending here.  see https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/36 for details.

**Pull request closed without merging**
